### ISSUE TITLE
Pyfa crashes at start: "ValueError: None is not a valid value for ownerID"

### ISSUE THREAD

**Issue by mipesom** [DarkFenX/Pyfa#274]
```bash
Traceback (most recent call last):
  File "pyfa.py", line 97, in <module>
    MainFrame()
  File "/home/mipesom/Apps/pyfa/gui/mainFrame.py", line 132, in __init__
    self.fitMultiSwitch = MultiSwitch(self.FitviewAdditionsPanel)
  File "/home/mipesom/Apps/pyfa/gui/multiSwitch.py", line 26, in __init__
    gui.chromeTabs.PFNotebook.__init__(self, parent)
  File "/home/mipesom/Apps/pyfa/gui/chromeTabs.py", line 112, in __init__
    self.tabsContainer = PFTabsContainer(self, canAdd=canAdd)
  File "/home/mipesom/Apps/pyfa/gui/chromeTabs.py", line 682, in __init__
    self.sFit = service.Fit.getInstance()
  File "/home/mipesom/Apps/pyfa/service/fit.py", line 78, in getInstance
    cls.instance = Fit()
  File "/home/mipesom/Apps/pyfa/service/fit.py", line 85, in __init__
    self.character = Character.getInstance().all5()
  File "/home/mipesom/Apps/pyfa/service/character.py", line 162, in all5
    eos.db.commit()
  File "/home/mipesom/Apps/pyfa/eos/db/saveddata/queries.py", line 426, in commit
    saveddata_session.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 790, in commit
    self.transaction.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2004, in flush
    self._flush(objects)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2122, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2086, in _flush
    flush_context.execute()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 487, in execute
    self.dependency_processor.process_saves(uow, states)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/dependency.py", line 755, in process_saves
    uowcommit, "add")
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/dependency.py", line 775, in _synchronize
    sync.clear(state, self.parent, self.prop.synchronize_pairs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/sync.py", line 77, in clear
    dest_mapper._set_state_attr_by_column(dest, dest.dict, r, None)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/mapper.py", line 2426, in _set_state_attr_by_column
    state.manager[prop.key].impl.set(state, dict_, value, None)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 696, in set
    value, old, initiator)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 705, in fire_replace_event
    self._init_append_or_replace_token())
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/util.py", line 118, in set_
    return validator(state.obj(), key, value)
  File "/home/mipesom/Apps/pyfa/eos/saveddata/character.py", line 197, in validator
    if map[key](val) == False: raise ValueError(str(val) + " is not a valid value for " + key)
ValueError: None is not a valid value for ownerID
```

**Comment by blitzmann** [comment]
I need a bit more information - which release or commit are you using? what were the steps you took to find this? Are you able to reproduce it?

It seems it is an error with validation of the ownerID value with stored characters. However, all my ownerID values are NULL in the database and I've never run into this issue before...

**Comment by mipesom** [comment]
I'm using the latest release 1.10.0 Scylla, downloaded yesterday. Happens every time I start the program. I don't find a saveddata.db.

**Comment by blitzmann** [comment]
`saveddata.db` is in your `~/.pyfa` directory (or `%userprofile%/.pyfa` on Windows)

**Comment by mipesom** [comment]
Did mail it to you. Used Pyfa in the past but not on this OS installation (Linux Mint 17.1). Have even erased .pyfa just now, but no difference, it's just created again and Pyfa crashes.

On Windows (7 64bit) the same Pyfa version works.

**Comment by blitzmann** [comment]
Very odd... Will look into it. Do previous versions still work? Start with v1.8.1 and go up from there...

**Comment by blitzmann** [comment]
Exactly which version of sqlalchemy are you using?

**Comment by xorxcel** [comment]
I just installed pyfa on arch linux via AUR, and got exactly the same error. 
I had python2-sqlalchemy version 1.0.4 installed on my system - Downgrading it to 0.9.9 fixed the problem.
So there seems to be some incompatibility to the 1.0 version of sqlalchemy.

**Comment by DarkFenX** [comment]
https://github.com/DarkFenX/Pyfa/commit/9cf20942f1001063a3b995517e6979d5d9dc1328
Try cherry-picking this commit from wx3 branch into master (or move changes manually) and re-test please.

**Comment by xorxcel** [comment]
I merged this patch into my pyfa installation and removed the ~/.pyfa directory - pyfa then successfully started and created the initial database with sqlalchemy 1.0, too.
Thank you for this fix.

**Comment by DarkFenX** [comment]
Fixed in e81f7eb765b24f4700f1b45f95451536830fcba2

**Comment by wolfwood** [comment]
this does not fix the issue when copying a fit:
Traceback (most recent call last):
  File "/home/wolfwood/repos/Pyfa/gui/sfBrowserItem.py", line 318, in OnLeftUp
    btn.DoCallback()
  File "/home/wolfwood/repos/Pyfa/gui/sfBrowserItem.py", line 49, in DoCallback
    self.callback()
  File "/home/wolfwood/repos/Pyfa/gui/shipBrowser.py", line 1607, in copyBtnCB
    self.copyFit()
  File "/home/wolfwood/repos/Pyfa/gui/shipBrowser.py", line 1611, in copyFit
    fitID = sFit.copyFit(self.fitID)
  File "/home/wolfwood/repos/Pyfa/service/fit.py", line 184, in copyFit
    eos.db.save(newFit)
  File "/home/wolfwood/repos/Pyfa/eos/db/saveddata/queries.py", line 415, in save
    commit()
  File "/home/wolfwood/repos/Pyfa/eos/db/saveddata/queries.py", line 426, in commit
    saveddata_session.commit()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 790, in commit
    self.transaction.commit()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 2004, in flush
    self._flush(objects)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 2122, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 2086, in _flush
    flush_context.execute()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 487, in execute
    self.dependency_processor.process_saves(uow, states)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/dependency.py", line 755, in process_saves
    uowcommit, "add")
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/dependency.py", line 775, in _synchronize
    sync.clear(state, self.parent, self.prop.synchronize_pairs)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/sync.py", line 77, in clear
    dest_mapper._set_state_attr_by_column(dest, dest.dict, r, None)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 2430, in _set_state_attr_by_column
    state.manager[prop.key].impl.set(state, dict_, value, None)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 696, in set
    value, old, initiator)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 705, in fire_replace_event
    self._init_append_or_replace_token())
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/util.py", line 118, in set_
    return validator(state.obj(), key, value)
  File "/home/wolfwood/repos/Pyfa/eos/saveddata/fit.py", line 301, in validator
    if map[key](val) == False: raise ValueError(str(val) + " is not a valid value for " + key)
ValueError: None is not a valid value for ownerID
