### ISSUE TITLE
Import evemon character file

### ISSUE THREAD

**Issue by blitzmann** [DarkFenX/Pyfa#325]
Saw this post:

https://www.reddit.com/r/Eve/comments/3c4f98/exporting_evemon_characters_to_eft/

I was gonna reply with "Well, in pyfa, you could just import the xml file" and then I realized this is not possible! Seems really easy, not sure why we don't already support it. Low priority.

**Comment by blitzmann** [comment]
Done

**Comment by tralafiti** [comment]
Still doesn't seem to work. Creating after plan xml format export in EveMon, importing in Pyfa 1.13.2 via import character file - noting happens, no error message, no new character, no updated skills on current character. 
Could you please have another look since this would be a realy helpful feature?

**Comment by blitzmann** [comment]
It's going to be included in the next update, which should come out this week.
